import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // Linux 文档自动生成侧边栏
  linux: [
    {
      type: 'autogenerated',
      dirName: 'linux', // 对应 docs/linux 目录
    },
  ],
  
  // Web 文档自动生成侧边栏
  web: [
    {
      type: 'autogenerated',
      dirName: 'web', // 对应 docs/web 目录
    },
  ],
  
  // 后端文档自动生成侧边栏
  back: [
    {
      type: 'autogenerated',
      dirName: 'back', // 对应 docs/back 目录
    },
  ],
};

module.exports = sidebars;
