name: Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [20]

    steps:
      - uses: actions/checkout@v4

      - name: Set node version to ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - run: corepack enable

      - name: Setup
        run: npm i -g @antfu/ni

      - name: Install
        run: nci

      - name: Build
        run: nr build

      - name: SSH Deploy
        uses: easingthemes/ssh-deploy@v2.1.6
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: '-avzr --delete'
          SOURCE: 'build/'
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: 'root'
          TARGET: '/usr/local/dockers/nginx/html/mdtest/'

      - name: Send Feishu Notification
        uses: junka/feishu-bot-webhook-action@main
        with:
          webhook: ${{ secrets.FEISHU_WEBHOOK_URL }}
          message: |
            {
              "msg_type": "post",
              "content": {
                "post": {
                  "zh_cn": {
                    "title": "构建部署 - ${{ job.status }}",
                    "content": [
                      [
                        {
                          "tag": "text",
                          "text": "**状态**: ${{ job.status }}\n**仓库**: ${{ github.repository }}\n**分支**: ${{ github.ref }}\n**触发者**: ${{ github.actor }}\n\n"
                        }
                      ],
                      [
                        {
                          "tag": "a",
                          "text": "查看详情",
                          "href": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                        }
                      ]
                    ]
                  }
                }
              }
            }
        if: always()
