name: Run Search Spider

on:
  workflow_run:
    workflows: ["Build & Deploy"]
    types:
      - completed

jobs:
  run-spider:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Download deployment artifact
        uses: actions/download-artifact@v4
        with:
          name: deploy-success
          path: .

      - name: Run Search Spider on remote server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker run --rm --env-file=/app/algolia/.env -e "CONFIG=$(python3 -c 'import json,sys; print(json.dumps(json.load(sys.stdin)))' < /app/algolia/docsearch.json)" algolia/docsearch-scraper


      - name: Sending Feishu Message
        uses: whatwewant/action-robot-feishu@v0.0.1
        with:
          url: ${{ secrets.FEISHU_WEBHOOK_URL }}
          title: notice
          text: |
            博客爬虫部署 - ${{ job.status }}
            repository: ${{ github.repository }}
            committer: ${{ github.actor }}
            compare: ${{ github.event.compare }}
            job status: ${{ job.status }}
