name: Run Search Spider

on:
  workflow_run:
    workflows: ["Build & Deploy"]
    types:
      - completed

jobs:
  run-spider:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Download deployment artifact
        uses: actions/download-artifact@v4
        with:
          name: deploy-success
          path: .

      - name: Run Search Spider on remote server
        uses: appleboy/ssh-action@v0.1.14
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker run --rm --env-file=/app/algolia/.env -e "CONFIG=$(python3 -c 'import json,sys; print(json.dumps(json.load(sys.stdin)))' < /app/algolia/docsearch.json)" algolia/docsearch-scraper

      - name: Send Feishu Notification
        uses: yanglbme/feishu-notify@v3.1.0  # 使用确切版本号
        with:
          url: ${{ secrets.FEISHU_WEBHOOK_URL }}
          title: "搜索爬虫 - ${{ job.status }}"
          content: |
            **状态**: ${{ job.status }}
            **仓库**: ${{ github.repository }}
            **触发工作流**: ${{ github.event.workflow_run.name }}
            **触发者**: ${{ github.event.workflow_run.actor.login }}
            
            [查看详情](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
        if: always()
